eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.cloud-eureka-server.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
---
spring:
  zipkin:
    baseUrl:  http://${eureka.instance.hostname}:9412
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    preferIpAddress: true